### PR TITLE
Added url parameter search

### PR DESCRIPTION
**Pull request by punit1108**
ADDING THE PREVIOUS PR #28 TO A SEPARATE BRANCH

In reference to the issue #27 

Additions : 
1. Search through paramters available, for eg, 
[https://punit1108.github.io/mfqp/index.html?search=asdf](url)
2. Callbacks added to the `worker.postMessage`

### CODE REVIEW

**Comment by icyflame** [comment]
@punit1108 Thanks a lot, this is a good one!

I saw your diff, and I saw that you were using the postMessage and then interpreting the data in the message etc. I saw the old code, and as far as I could see, that part is used only for the asynchronous download of the Data JSON.

What we want to do here is rather simple. So, is there a reason why something like this will not work?

1. Just after [line 153](https://github.com/metakgp/mfqp/blob/904569437dbbc44ef1051017912e0ea776538bae/index.html#L153) we parse the query string and get the query.

2. We call `$("#query").val(search_query); search()` These function calls will read the query and do the heavy lifting required.

I quickly tested this out in the console (by making `search` a global function) and it worked.

image
***
image

Also, I would prefer if you used a library for query parsing instead of re-inventing the wheel. [This one](https://websanova.com/plugins/url) looks good, you are free to search for a better one.

**Comment by punit1108** [comment]
@icyflame Thanks for your review.

The points that you raised : 

1. Even after populating the `input`, the search is being triggered by `keydown`. If i populate the `input` at the starting of the script, the `data` from `data.json` has not been loaded yet (which is a AJAX call and file being heavy takes time to load) without which no query will work. So, therefore i have taken a `callback` from the `postMessage` which loads the `data.json` to trigger the search event.

2. The reason why your console script word was the `data.json` got loaded before you wrote the script in the console. But, mind you, it takes time when the page loads and the javascript runs asynchronously. (ie, Writing `$('#query').val(query_string);search()` at the start of the javascript wont work.)

I hope this clears the doubt you had. Please write back for any other clarification.

**Comment by icyflame** [comment]
@punit1108 Ah! That's a good explanation.

Like you said, though, once the JSON has been loaded, after that we are free to fill up the search box and let the present code take over. We needn't get entangled in the message sending.

Check out: https://github.com/icyflame/mfqp/commit/700b2aad09ac54f6baaf74e108fd43c854afd0a9 That works, and is a far smaller patch. What do you think? :slightly_smiling_face: 

Also, [jquery-url](https://github.com/websanova/js-url) is a great library and handles a lot of corner cases. The minified version is only 4 KB, it is still being maintained and updated frequently. I think we can use that library.

**Comment by punit1108** [comment]
@icyflame : So the reason why we need to entangle with the message sending is

- Earlier the worker was not sending any callback when the loading of `data.json` finished, so we need to know when it gets over and then call the `search` function. Hence the callback function.

- If nothing else, the `callbacks` in the worker messaging only increases the utility of the worker.

I will add the `jquery-url` as you suggested.

**Comment by icyflame** [comment]
@punit1108 I understood your point about _why_ we need to do it as you have done it.

But there is also another approach: https://github.com/icyflame/mfqp/commit/700b2aad09ac54f6baaf74e108fd43c854afd0a9

This approach is much smaller and takes advantage of the existing code.

I think that we should get someone else's comments because we (obviously) have biases for _our_ method of solving this problem :smile: 

@amrav @vivekiitkgp @hargup: What are your comments on the two approaches? Which one do you prefer? (My approach is the commit https://github.com/icyflame/mfqp/commit/700b2aad09ac54f6baaf74e108fd43c854afd0a9, Punit's approach is this pull request)

**Comment by amrav** [comment]
So there are a few different issues here:

1. What happens if you run a query, and data.json hasn't loaded yet?
2. Where do you put the callback for running a query from the query params?
3. How do you structure the code in a way that makes it easy to understand?

I'll avoid offering any suggestions here, but try to do the simplest thing possible!

**Comment by punit1108** [comment]
@icyflame just tested your code, the code works. i couldnt make it work when i tried your approach (before formulating mine), may have made a mistake. :+1:

**Pull request closed without merging**
