### PR TITLE
Add Share Buttons

### LINKED ISSUE #35: Add a button on the page to share the present search
- This should create the URL `host/?search=<QUERY>` and copy it to the clipboard.

### PR DESCRIPTION
**Pull request by thealphadollar**
This PR fixes #35 

Four share buttons have been added on the page as follows; and their image assets have been added to resources/images. Following is the look of the mfqp page (hosted on my local host) after the changes.

screenshot from 2018-10-06 23-50-31

1. Facebook share button: A share popup is opened in a new tab with the query URL specified in the issue. No screenshot could be captured since it doesn't allow sharing for non-certified connections.

2. Twitter share button: A share pop up opens in a new tab with the following details.

screenshot from 2018-10-06 23-50-28

3. Mail share: Users are also given the benefit to share using `mailto` hyperlink
screenshot from 2018-10-06 23-50-18

4. Copy link: On phone, to share on whatsapp and messenger, user can copy the link to the share button as well.
screenshot from 2018-10-06 23-50-09

**change severity: moderate**
_changes tested on **Chrome 69.0** on **Debian 9**_

### CODE REVIEW

**Comment by thealphadollar** [comment]
@icyflame @athityakumar @ghostwriternr Please review.

**Comment by thealphadollar** [comment]
@nishnik  @icyflame @amrav @zorroblue Please review.

**Comment by amrav** [comment]
Hmm, not sure I understand the use case for a share button - why isn't copying the current URL sufficient? (So the alternative implementation I'm suggesting is modifying the URL in real-time to match the current query)

Slightly more obvious to the user would be a (very plain) clipboard icon next to the search box which copies the current deeplink onto the clipboard. But the social media share buttons kill the minimalist vibe IMO :)

**Comment by icyflame** [comment]
Agree with @amrav. This seems like too much. They can copy the link (the button at the end of each link can be the bootstrap clipboard icon, that will be clean and in line with the design of the other elements on the page)

**Comment by thealphadollar** [comment]
@icyflame @amrav I've minimalized the share button and now there is only option to copy link alongside the search box.

screenshot from 2018-11-02 12-16-03

**Comment by thealphadollar** [comment]
@icyflame @amrav ping.

**Comment by icyflame** [comment]
I am really not sure we need a button to "copy link". It's fairly simple and most people know it. Why do you think it's necessary, @thealphadollar? 🤔

**Comment by thealphadollar** [comment]
Well, firstly because we do not show the updated url with search. So, if I ask my friend to search for maths paper, the results could be different depending on what he queries for.

WIth a copy link button I can make sure we have the same results.

**Comment by icyflame** [comment]
AH! I see what you mean, We don't have a way to tell the user what the actual link to share is (although we do have a link to share the exact search) Hmmm. 🤔

**Comment by thealphadollar** [comment]
So, please merge this :) And deploy.

cc/ @amrav

**Comment by icyflame** [comment]
@thealphadollar Actually, I think the right thing to do here would be to make it so that the URL gets updated when they search, so that they can simply copy the link from the address bar. I have seen some places that it is possible _without_ refreshing the page but I couldn't get it to work when I was first merging #30. It would be great if you could look into that.

**Comment by thealphadollar** [comment]
Well, @icyflame If you look closely and see that if that is possible certainly it's a HUGE security flaw. Any spam website will be able to change URL at will, and hence will cause issues. Here is a stack-overflow discussion about the same.

https://stackoverflow.com/questions/12508225/how-do-we-update-url-or-query-strings-using-javascript-jquery-without-reloading

I don't think there is any other way; it is restricted by browser though the code is easy.

**Comment by icyflame** [comment]
Oh! I didn't think of that. But the idea I saw was from GitHub, where you can press `y` and then the link changes to the link to a fixed object instead of the branch name.

**Comment by amrav** [comment]
You can change the query param only without reloading the page.

**Comment by thealphadollar** [comment]
@amrav And not the URL, right? So the user has no way to ask someone to open exact result unless he copies his query and sends it to someone.

Copying URL makes it a lot easy.

**Comment by amrav** [comment]
The query param is part of the URL.

**Comment by icyflame** [comment]
Yeah, as you type, the URL's query param part will change to what the present query is. When the user wants to share a search result, they can copy the URL from their browser and share it. As long as we can do that, there's no need to have a separate button on the UI. Sorry, @thealphadollar! 😢

**Comment by thealphadollar** [comment]
Should I implement it instead of this then? @icyflame

**Comment by icyflame** [comment]
@thealphadollar that would be great! Thanks for working on this, @thealphadollar! 👍

**Comment by thealphadollar** [comment]
I've added the functionality which updates the URL on the go.

screenshot from 2018-12-08 01-32-27

@amrav @icyflame

**Comment by icyflame** [comment]
@thealphadollar thanks!

I cloned this repository and tried to test on Safari (using `python -m SimpleHTTPServer`) but that didn't work (??) Any idea why that might be? I pulled your branch. The top commit is c652ae8

**Comment by thealphadollar** [comment]
As I had informed earlier, the method used is not supported by all browsers due to security concerns. Below are two references I pulled up regarding Safari:
- https://stackoverflow.com/questions/10941553/pushstate-popstate-safari-5-not-returning-window-history-state
- https://github.com/aurelia/history-browser/issues/34

Quoting one response:
> This issue behaves as intended based on the following:
This is by design. We fixed a security bug in iOS that abused pushState/replaceState.

**Comment by icyflame** [comment]
The link you shared is for Safari 5. I am using Safari 12. The question in the link is nearly 6 years old. It doesn't apply here.

`pushState` / `replaceState` is a HTML5 feature and works on most modern browsers. It's support can be checked [here][1].

[1]: https://caniuse.com/#search=pushstate

**Comment by thealphadollar** [comment]
@icyflame I've tested it on Firefox and Chrome; it is working on both. I've no way to test it on Safari. Can you please look into the problem using Dev-Tools of Safari and give me more details.

**Comment by icyflame** [comment]
@thealphadollar I will do that in a while, sorry about the delay though, I am not sure when I'll be able to get to it! 😞

**Comment by thealphadollar** [comment]
Ping @icyflame

**Comment by thealphadollar** [comment]
Ping @icyflame

**Comment by icyflame** [comment]
@thealphadollar Tested on Safari. Great patch! Thanks for working on this!

**Review by icyflame — APPROVED** [review]
Shivam: Please go ahead and merge.

**Pull request merged**
